### ISSUE TITLE
Strange Error while loading opal-d3

### ISSUE THREAD

**Issue by mistergibson** [taw/opal-d3#2]
I compiled opal-d3 into my bootstrap.js file and upon loading it appears that something in arc/radial_area calls an 'underscore' method that doesn't exist. Just thought I'd bring this to your attention.

Browser Console Output: (Chrome latest stable)

gxg_bootstrap.min.js:1 Uncaught $NoMethodError {name: "underscore", message: "undefined method `underscore' for "innerRadius":String", args: Array(0), stack: "underscore: undefined method `underscore' for "innerRadius":String"}args: Array(0)length: 0__proto__: Array(0)message: "undefined method `underscore' for "innerRadius":String"name: "underscore"stack: "underscore: undefined method `underscore' for "innerRadius":String"__proto__: $NameError$$class: singleton_class_alloc {$$id: 58, $$is_a_module: true, $$inc: Array(0), $$name: "NoMethodError", $$const: {…}, …}$args: ƒ ()$initialize: ƒ $$initialize(message,name,args)args: NilClass_alloc {$$id: 4, apply: ƒ, call: ƒ}constructor: ƒ $NoMethodError()__proto__: $StandardError
raise @ gxg_bootstrap.min.js:1
method_missing @ gxg_bootstrap.min.js:1
method_missing_stub @ gxg_bootstrap.min.js:1
attribute_d3_block @ gxg_bootstrap.min.js:1
(anonymous) @ gxg_bootstrap.min.js:1
(anonymous) @ gxg_bootstrap.min.js:1
Opal.modules.d3/arc @ gxg_bootstrap.min.js:1
Opal.load @ gxg_bootstrap.min.js:1
Opal.require @ gxg_bootstrap.min.js:1
(anonymous) @ gxg_bootstrap.min.js:1
(anonymous) @ gxg_bootstrap.min.js:1

**Comment by taw** [comment]
Hi,

The released gem version doesn't use it.

On github version, that's supposed to come from opal-activesupport gem.

Not sure why it's not working. I guess I could inline it, as it's a very
simple method.

**Comment by mistergibson** [comment]
I tried to compile a little different way and got this: (I looked at d3 - there is a d3.geoCentroid that returns a centroid function ... but that's all I found)

gxg_bootstrap.min.js:1 Uncaught $NameError {name: NilClass_alloc, message: "undefined native method `centroid' for class `D3::ArcGenerator'", stack: "undefined native method `centroid' for class `D3::ArcGenerator'"}message: "undefined native method `centroid' for class `D3::ArcGenerator'"name: NilClass_alloc {$$id: 4, apply: ƒ, call: ƒ}stack: "undefined native method `centroid' for class `D3::ArcGenerator'"__proto__: $StandardError
Opal.alias_native @ gxg_bootstrap.min.js:1
alias_native @ gxg_bootstrap.min.js:1
(anonymous) @ gxg_bootstrap.min.js:1
(anonymous) @ gxg_bootstrap.min.js:1
Opal.modules.opal/d3/arc @ gxg_bootstrap.min.js:1
Opal.load @ gxg_bootstrap.min.js:1
Opal.require @ gxg_bootstrap.min.js:1
Opal.modules.opal/d3 @ gxg_bootstrap.min.js:1
Opal.load @ gxg_bootstrap.min.js:1
Opal.require @ gxg_bootstrap.min.js:1
Opal.modules.opal-d3 @ gxg_bootstrap.min.js:1
Opal.load @ gxg_bootstrap.min.js:1
Opal.require @ gxg_bootstrap.min.js:1
(anonymous) @ gxg_bootstrap.min.js:1
(anonymous) @ gxg_bootstrap.min.js:1

**Comment by mistergibson** [comment]
I've tried a few ways and get errors. Perhaps you can give me a run down on how you go about requiring it? Sounds silly, but I'm obviously doing it wrong. Got:

gxg_bootstrap.min.js:1 Uncaught $NoMethodError {name: "append_path", message: "undefined method `append_path' for Opal", args: Array(1), stack: "append_path: undefined method `append_path' for Opal"}
raise @ gxg_bootstrap.min.js:1
method_missing @ gxg_bootstrap.min.js:1
method_missing_stub @ gxg_bootstrap.min.js:1
Opal.modules.opal/activesupport @ gxg_bootstrap.min.js:1
Opal.load @ gxg_bootstrap.min.js:1
Opal.require @ gxg_bootstrap.min.js:1
Opal.modules.opal-activesupport @ gxg_bootstrap.min.js:1
Opal.load @ gxg_bootstrap.min.js:1
Opal.require @ gxg_bootstrap.min.js:1
(anonymous) @ gxg_bootstrap.min.js:1
(anonymous) @ gxg_bootstrap.min.js:1

**Comment by taw** [comment]
Well, there's demo app included in the repo. Is that of any help?

**Comment by mistergibson** [comment]
I got it starting to load, but ran into a snag with d3/arc.rb - evidently, you are aliasing an non-existent native method - or so says the error. Now, there IS a d3.geoCentroid that does exist and it resolves to a function called 'centroid'. I'm not sure why Opal can't see it and was hoping you might have an idea. Here is the console output:

"undefined native method `centroid' for class `D3::ArcGenerator'"

Opal.alias_native | @ | gxg_bootstrap.min.js:1
-- | -- | --
  | alias_native | @ | gxg_bootstrap.min.js:1
  | (anonymous) | @ | gxg_bootstrap.min.js:1
  | (anonymous) | @ | gxg_bootstrap.min.js:1
  | Opal.modules.opal/d3/arc | @ | gxg_bootstrap.min.js:1
  | Opal.load | @ | gxg_bootstrap.min.js:1
  | Opal.require | @ | gxg_bootstrap.min.js:1
  | Opal.modules.opal/d3 | @ | gxg_bootstrap.min.js:1
  | Opal.load | @ | gxg_bootstrap.min.js:1
  | Opal.require | @ | gxg_bootstrap.min.js:1
  | Opal.modules.opal-d3 | @ | gxg_bootstrap.min.js:1
  | Opal.load | @ | gxg_bootstrap.min.js:1
  | Opal.require | @ | gxg_bootstrap.min.js:1
  | require_tree | @ | gxg_bootstrap.min.js:1
  | (anonymous) | @ | gxg_bootstrap.min.js:1
  | (anonymous) | @ | gxg_bootstrap.min.js:1

**Comment by taw** [comment]
I don't think I can do anything about it.

I guess `opal-d3` could use a big refresh to latest versions of `opal` and `d3`, but i don't have time for it right now.
